spring:
  http:
    servlet:
      encoding:
        charset: UTF-8
        enabled: true
        force: true
  application:
    name: erp
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/buildflow}
    username: ${DB_USERNAME:buildflow_dev}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  liquibase:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION:86400000}

app:
  cors:
    allowed-origin:
      - https://buildflow-ochre-nine.vercel.app
      - http://localhost:3000
      - https://buildflow-six.vercel.app
